# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "AIDEme"
  url = "#intro"
  weight = 10

[[main]]
  name = "Members"
  url = "#members"
  weight = 20
  #identifier = "something"

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 30
  
[[main]]
  name = "Datasets"
  url = "#datasets"
  weight = 40
  #Parent = "something"

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 50

[[main]]
  name = "Funding"
  url = "#funding"
  weight = 60

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
